buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.11.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0"
        classpath "com.google.devtools.ksp:symbol-processing-gradle-plugin:2.3.0"
    }
}
